title: Akash Induwara
logo: /assets/img/headshot_circle.png
#description: text below image
personal_info:
  name: "Akash Induwara"
  full_name: "Senevirathne Arachchige Akash Induwara Nimmath"
  initials: "S.A.A.I. Nimmath"
  date_of_birth: "2002.02.25"
  age: 22
  gender: "Male"
  nationality: "Sinhala"
  civil_status: "Unmarried"
  religion: "Buddhism"
  contact:
    phone: "076-1353671"
    address: "No 22/2, Near the Tank, Kiripedda, Karandeniya"
    email: "nimmathakash@gmail.com"

languages:
  - Sinhala
  - English

skills:
  - Communication
  - Leadership
  - Time Management
  - Teamwork
  - Creativity

education:
  gce_advanced_level:
    year: 2023
    subjects:
      Biology: "C"
      Chemistry: "C"
      Physics: "S"
  gce_ordinary_level:
    year: 2018
    subjects:
      Sinhala: "A"
      Buddhism: "A"
      Mathematics: "A"
      Science: "A"
      History: "A"
      English: "A"
      Literature: "A"
      Commerce: "C"
      ICT: "B"
  bachelor_degree:
    title: "Bachelor of Science in Biotechnology"
    institution: "Sri Lanka Institute of Information Technology - Malabe"

extracurricular_activities:
  volunteer_work: "Participated in community service projects or charity events."
  club_membership: "Member of IT, Business clubs at Dharmashoka College."
  sports_participation: "Represented the school in inter-school cricket tournaments."

declaration:
  statement: "I do hereby certify that the particulars furnished above are true and correct to the best of my knowledge and belief."
  signature: ""
  date: ""

show_downloads: true
theme: jekyll-theme-minimal
